### ISSUE TITLE
Consider renaming package and entry points

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-babel#10]
Since this isn't an OCDS-specific package, we can consider renaming it. For example, the package works with all specifications that combine JSON Schema with CSV codelists, so we might replace "OCDS" with "JSCC".

However, unless there is significant resistance to using the library as-is, it's not worth the effort to rename it here and in all repositories using it.

**Comment by robredpath** [comment]
In the short term, it could be good to define what "like OCDS or BODS" means - something to make it clear that "like" means "specification that combine JSON Schema with CSV codelists".

I'm not aware of any particular resistance to using the current name as it's not a part of the infrastructure that most people will ever see. However, it would definitely be cleaner to have a more generic name. Could we fork at this point, rename, and refactor applications as-and-when we happen to be working on them? So, we don't break anything now, but over time we get to a cleaner place?

**Comment by jpmckinney** [comment]
The pypi package will remain available in perpetuity, so there is no reason to fork, as nothing will break, as everything uses a released pypi package. We can simply rename the repository, etc.

We can edit the opening paragraph to be more explicit, e.g. anything that uses these [JSON Schema extensions](https://os4d.opendataservices.coop/development/schema/#extended-json-schema).
